/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ip.multicast.stream.screen.video;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.Timer;
import receive.ScreenReceive;
import receive.VoiceReceive;

/**
 *
 * @author Admin
 */
public class Client extends javax.swing.JFrame {

    Thread threadReceiveVideo, threadReceiveSound, threadReceiveChat;
    ScreenReceive screenReceive;
    VoiceReceive voiceReceive;

    public volatile boolean isRunningStream = false;
    public volatile boolean isStreamVideo = true;
    public volatile boolean isStreamAudio = true;
    public volatile int pts = 0;
    public volatile double mBs = 7.1f;

    public Client() {
        initComponents();
        // cập nhật Status : Connected <True>  Stream <Video>  Audio<on>    pts <60>   speed <7.2MBs>   
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(screenReceive== null) return;
                double tmp  = screenReceive.getMB()/8/1024;
                lblStatus.setText("Status : Connected <" + isRunningStream + ">  Stream <Video: " + isStreamVideo + ">  <Audio:" + isStreamAudio + ">    pts <" + screenReceive.getPts() + ">   speed <" + String.format("%3.2f", tmp) + " MBs>");
                screenReceive.setMB(0);screenReceive.setPts(0);
                lblStatus.revalidate();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGroupVideo = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnMain = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        pnChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatView = new javax.swing.JTextArea();
        pnChatView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnHead = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        txtIpPort = new javax.swing.JTextField();
        btnStartConnect = new javax.swing.JToggleButton();
        lblStatus = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        setMinimumSize(new java.awt.Dimension(960, 480));

        jSplitPane1.setDividerLocation(700);
        jSplitPane1.setResizeWeight(0.8);
        jSplitPane1.setToolTipText("");

        pnMain.setBackground(new java.awt.Color(255, 0, 51));
        pnMain.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(pnMain);

        pnMenu.setBackground(new java.awt.Color(102, 255, 102));
        pnMenu.setMaximumSize(new java.awt.Dimension(500, 1080));
        pnMenu.setMinimumSize(new java.awt.Dimension(200, 125));
        pnMenu.setLayout(new java.awt.BorderLayout());

        pnChat.setBackground(new java.awt.Color(0, 153, 153));
        pnChat.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtChatView.setColumns(20);
        txtChatView.setRows(5);
        jScrollPane1.setViewportView(txtChatView);

        pnChat.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnChatView.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Chat >>");
        pnChatView.add(jLabel3, java.awt.BorderLayout.WEST);

        jTextField1.setColumns(15);
        pnChatView.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Send");
        pnChatView.add(jButton1, java.awt.BorderLayout.EAST);

        pnChat.add(pnChatView, java.awt.BorderLayout.SOUTH);

        pnMenu.add(pnChat, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(pnMenu);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pnHead.setBackground(new java.awt.Color(255, 255, 255));
        pnHead.setLayout(new java.awt.BorderLayout());

        lblHeader.setText("Chào mừng bạn đến với demo về Multichat sử dụng ip multicast");
        pnHead.add(lblHeader, java.awt.BorderLayout.NORTH);

        txtIpPort.setText("224.0.0.251:4444:5555:6666");
        pnHead.add(txtIpPort, java.awt.BorderLayout.CENTER);

        btnStartConnect.setText("Connect ...");
        btnStartConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartConnectActionPerformed(evt);
            }
        });
        pnHead.add(btnStartConnect, java.awt.BorderLayout.EAST);

        lblStatus.setText("Status : Connected <True>  Stream <Video>  Audio<on>    pts <60>   speed <7.2MBs>   ");
        pnHead.add(lblStatus, java.awt.BorderLayout.SOUTH);

        jLabel6.setText("IP & Port: ");
        pnHead.add(jLabel6, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnHead, java.awt.BorderLayout.PAGE_START);

        pnBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnBottom.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Lê Minh Trung - 13T4 - Đồ Án Lập Trình  Mạng");
        pnBottom.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Stream and Chat");
        pnBottom.add(jLabel2, java.awt.BorderLayout.EAST);

        getContentPane().add(pnBottom, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartConnectActionPerformed
        if (isRunningStream) {
            threadReceiveVideo.stop();
            isRunningStream = false;
            isStreamVideo = false;
            isStreamAudio = false;
            pts = 0;
            mBs = 0;
        } else {
            String ipPort = txtIpPort.getText();
            String[] split = ipPort.split(":");
            int port = Integer.parseInt(split[1]);
            try {
                screenReceive = new ScreenReceive(pts,mBs,pnMain, split[0], port);
                threadReceiveVideo = new Thread(screenReceive);
                threadReceiveVideo.start();
                isStreamVideo = true;
            } catch (Exception e) {
            }
            try {
                port = Integer.parseInt(split[2]);
                voiceReceive = new VoiceReceive(mBs,split[0], port);
                threadReceiveSound = new Thread(voiceReceive);
                threadReceiveSound.start();
                isStreamAudio = true;
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_btnStartConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnStartConnect;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnChat;
    private javax.swing.JPanel pnChatView;
    private javax.swing.JPanel pnHead;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.ButtonGroup rdGroupVideo;
    private javax.swing.JTextArea txtChatView;
    private javax.swing.JTextField txtIpPort;
    // End of variables declaration//GEN-END:variables
}
